### ISSUE TITLE
can't be assigned to the parameter type 'ImageStreamListener

### ISSUE THREAD

**Issue by jeson-jin** [fluttercandies/extended_image#16]
. Dart VM version: 2.3.1
. Flutter 1.7.2-pre.30 • channel master

..../extended_image-0.4.1/lib/src/extended_imag
e.dart:723:59: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the
parameter type 'ImageStreamListener'.

**Comment by youngxhui** [comment]
same problem

**Comment by zmtzawqlp** [comment]
better to use stable flutter version(1.5.4hotfix), new flutter version has changed many api.. i will update them in dev branch when i have time.

**Comment by vahidHossaini** [comment]
replace

**Comment by vahidHossaini** [comment]
replace 
`return oldImageStream?.removeListener( _updateImage);`
with
`return oldImageStream?.removeListener(new ImageStreamListener(_updateImage) );`

**Comment by karnadii** [comment]
same here, any fix?
```
file:///home/karnadi/Android/flutter/.pub-cache/git/extended_image-e642b31021f446a2868f35a70e745e6c1d8fa1d1/lib/src/ext
ended_image.dart:733:59: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter
type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' 
 ('file:///home/karnadi/Android/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart'
 ('file:///home/karnadi/Android/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
    if (_isListeningToStream) _imageStream.removeListener(_handleImageChanged);
                                                          ^             
file:///home/karnadi/Android/flutter/.pub-cache/git/extended_image-e642b31021f446a2868f35a70e745e6c1d8fa1d1/lib/src/ext
ended_image.dart:744:53: Error: No named parameter with the name 'onError'.
      _imageStream.addListener(_handleImageChanged, onError: _loadFailed);
                                                    ^^^^^^^             
file:///home/karnadi/Android/flutter/.pub-cache/git/extended_image-e642b31021f446a2868f35a70e745e6c1d8fa1d1/lib/src/ext
ended_image.dart:749:51: Error: No named parameter with the name 'onError'.
    _imageStream.addListener(_handleImageChanged, onError: _loadFailed);
                                                  ^^^^^^^               
file:///home/karnadi/Android/flutter/.pub-cache/git/extended_image-e642b31021f446a2868f35a70e745e6c1d8fa1d1/lib/src/ext
ended_image.dart:755:33: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter
type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' 
 ('file:///home/karnadi/Android/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart'
 ('file:///home/karnadi/Android/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
    _imageStream.removeListener(_handleImageChanged);       
```

**Comment by zmtzawqlp** [comment]
wait for stable version update, please fix it in local at the moment

**Comment by karnadii** [comment]
can't you make two different version like https://github.com/mchome/flutter_advanced_networkimage did? I can't change to stable channel because there are fix that only in master channel.

**Comment by zmtzawqlp** [comment]
i will do this at dev branch, and may be you can link it like github url

extended_image:
    git:
      url: https://github.com/fluttercandies/extended_image/dev

**Comment by karnadii** [comment]
thanks.

**Comment by zmtzawqlp** [comment]
done, please try link it as git 549af1104e55b9494f014d8e7f8e55cb5882d729

**Comment by ThinkDigitalSoftware** [comment]
> i will do this at dev branch, and may be you can link it like github url
> 
> extended_image:
> git:
> url: https://github.com/fluttercandies/extended_image/dev

For those who don't understand indentation for yaml files, paste it like this.
```yaml
extended_image:
git:
url: https://github.com/fluttercandies/extended_image/dev

**Comment by zmtzawqlp** [comment]
please take a look  https://flutter.dev/docs/development/packages-and-plugins/using-packages

**Comment by KsAmJ** [comment]
> > i will do this at dev branch, and may be you can link it like github url
> > extended_image:
> > git:
> > url: https://github.com/fluttercandies/extended_image/dev
> 
> For those who don't understand indentation for yaml files, paste it like this.
> 
> ```yaml
> dependencies:
>   extended_image:
>     git:
>       url: https://github.com/fluttercandies/extended_image/dev
> ```

this doesn't work
show not found 
also if the 0.5.2 is up why it is not reflected on https://pub.dev ???

how to use the package now as i am stuck

**Comment by zmtzawqlp** [comment]
use  following code to link to dev at the moment，

``` dart
  extended_image:
    git:
      url: https://github.com/fluttercandies/extended_image.git
      ref: 549af1104e55b9494f014d8e7f8e55cb5882d729
```

i will update codes to stable 1.7.8 as soon as possible，

**Comment by ThinkDigitalSoftware** [comment]
Or I think you can just put dev as the ref

**Comment by OPY-bbt** [comment]
@zmtzawqlp  I get below error
```
Git error. Command: git rev-list --max-count=1 549af1104e55b9494f014d8e7f8e55cb5882d729
fatal: bad object 549af1104e55b9494f014d8e7f8e55cb5882d729     
```

**Comment by ThinkDigitalSoftware** [comment]
@OPY-bbt just copy and paste this 👇🏾
```yaml
extended_image:
    git:
      url: https://github.com/fluttercandies/extended_image.git
      ref: dev
```
<img width="594" alt="Screen Shot 2019-07-10 at 10 42 34 AM" src="https://user-images.githubusercontent.com/23037821/60991551-99128a00-a2ff-11e9-905f-611c75ec1a42.png">

**Comment by OPY-bbt** [comment]
@ThinkDigitalSoftware dont work, some git config cause this?
```
Git error. Command: git rev-list --max-count=1 dev


fatal: ambiguous argument 'dev': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:

'git <command> [<revision>...] -- [<file>...]'

pub get failed (69) -- attempting retry 1 in 1 second...
```

**Comment by ThinkDigitalSoftware** [comment]
Can you paste your code from your pubspec.yaml?

**Comment by OPY-bbt** [comment]
```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: 2.1.0
  fluwx: ^1.0.3
  crypto: ^2.0.6
  fluro: ^1.4.0
  shared_preferences: ^0.5.3+1
  flutter_swiper: ^1.1.6
  flutter_staggered_grid_view:  ^0.3.0
  webview_flutter: ^0.3.9+1
  image_picker_saver: ^0.3.0
  extended_image:
    git:
      url: https://github.com/fluttercandies/extended_image.git
      ref: dev
  oktoast: ^2.1.8
  shimmer: ^1.0.0
  permission_handler: '^3.1.0'
  pedantic: '^1.5.0'
  flutter_webview_plugin:
    path: ./flutter_webview_plugin-message
  device_info: ^0.4.0+2
  in_app_purchase: ^0.2.0+2

```
