### ISSUE TITLE
ERROR:   _invertColors = MediaQuery.of(context, nullOk: true)?.invertColors ??

### ISSUE THREAD

**Issue by hello-paulvin** [fluttercandies/extended_image#310]
Runing flutter doctor
![Screenshot 2021-03-04 120727](https://user-images.githubusercontent.com/68385854/109954969-38a93b00-7ce2-11eb-8e98-f68957ca3f5b.png)

Error:
![Screenshot 2021-03-04 120854](https://user-images.githubusercontent.com/68385854/109955118-6bebca00-7ce2-11eb-8bf8-da08f458e126.png)

Before this error happen[Timeline]:
On trying to run my app.

**Comment by BartusZak** [comment]
The same here.

**Comment by zmtzawqlp** [comment]
use dev version for now . #258
i will support null-safety and non-null-safety later

**Comment by BartusZak** [comment]
Confirmed:

```
  extended_image:
    dependency: "direct overridden"
    description:
      name: extended_image
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.5.0-dev"
```

```yaml
dependency_overrides:
  extended_image: ^1.5.0-dev
```

Allows to start app with `Flutter: 2.0.0`

Another error occured (probably not related to `extended_image`)

```
Expected a value of type 'String', but got one of type 'bool'
```
