### ISSUE TITLE
Error: Null safe libraries are not allowed to export declarations from of opt-out libraries

### ISSUE THREAD

**Issue by Mohammad-Adam** [fluttercandies/extended_image#323]
```
../../flutter/.pub-cache/hosted/pub.dartlang.org/http_client_helper-2.0.2/lib/http_client_helper.dart:5:1: Error: Null safe libraries are not allowed to export declarations from of opt-out libraries.
export 'package:http/http.dart';
^
../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.0.0/lib/extended_image_library.dart:3:1: Error: Null safe libraries are not allowed to export declarations from of opt-out libraries.
export 'package:http_client_helper/http_client_helper.dart' hide Response;
^
../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-4.0.0/lib/extended_image.dart:3:1: Error: Null safe libraries are not allowed to export declarations from of opt-out libraries.
export 'package:extended_image_library/extended_image_library.dart';
^


FAILURE: Build failed with an exception.
```

# and I have this in pubspec.yaml:
```
dependency_overrides:
  http: '>=0.12.2'
  intl: '>=0.16.1'
  http_parser: '>=4.0.0'
  path_provider: '>=2.0.0'
  device_info: '>=2.0.0'
  time: '>=2.0.0'
  url_launcher: '>=6.0.0'
```
