### ISSUE TITLE
build error in flutter 1.10.15, ExtendedMemoryImageProvider.load' has fewer positional arguments than those of overridden method 'MemoryImage.load'.

### ISSUE THREAD

**Issue by mana-ai** [fluttercandies/extended_image#80]
pub.flutter-io.cn/extended_image_library-0.1.8/lib/src/extended_me
mory_image_provider.dart:12:24: Error: The method 'ExtendedMemoryImageProvider.load' has fewer positional arguments
than those of overridden method 'MemoryImage.load'.
  ImageStreamCompleter load(MemoryImage key) {

**Comment by zmtzawqlp** [comment]
please use preview-version for now, i will fix it as soon as possible

**Comment by zmtzawqlp** [comment]
please provide version of flutter sdk  , i didn't see any problem from my side

**Comment by Codered81** [comment]
Cached_network_image package has the exact same issue, they provided an RC as a temporary fix due to the breaking change in Flutter SDK.

**Comment by zmtzawqlp** [comment]
ok, think, I see，i will fix it in dev branch as soon as possible. you can use it as git url

**Comment by zmtzawqlp** [comment]
please add following code to your pubspec.yaml for now. i have fixed build error in dev branch, i will publish it to pub.com when 1.10.15 is in stable branch
``` yaml
dependency_overrides:
  extended_image_library:
    git:
        url: https://github.com/fluttercandies/extended_image_library.git
        ref: dev
```

**Comment by ThinkDigitalSoftware** [comment]
> please add following code to your pubspec.yaml for now. i have fixed build error in dev branch, i will publish it to pub.com when 1.10.15 is in stable branch
> 
```yaml
dependency_overrides:
  extended_image_library:
    git:
        url: https://github.com/fluttercandies/extended_image_library.git
        ref: dev
```
Weird, when I get it from git like you mentioned, it pulls version 0.1.9 even though that's not what it says on that branch...
